In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn import linear_model


df=pd.read_csv("/content/drive/MyDrive/Dataset/API_NY.GDP.PCAP.CD_DS2_en_csv_v2_121663.csv", skiprows=4)

In [ ]:
df.isna().sum()

Country Name        0
Country Code        0
Indicator Name      0
Indicator Code      0
1960              115
                 ...
2022                9
2023               15
2024               26
2025              266
Unnamed: 70       266
Length: 71, dtype: int64

In [ ]:
df=df.drop(columns=['Unnamed: 70','2025'])

In [ ]:
df.isna().sum().sum()

np.int64(2729)

In [ ]:
df.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Aruba,ABW,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,27458.220154,27441.550214,28440.041688,30082.158423,30645.890602,22759.807175,26749.329609,30975.998912,35718.753119,39498.594129
1,Africa Eastern and Southern,AFE,GDP per capita (current US$),NY.GDP.PCAP.CD,186.089204,186.909053,197.367547,225.400079,208.962717,226.836135,...,1498.875240,1334.470500,1528.104224,1552.073722,1507.085600,1351.591669,1562.416175,1679.327622,1571.449189,1615.396356
2,Afghanistan,AFG,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,565.569730,522.082216,525.469771,491.337221,496.602504,510.787063,356.496214,357.261153,413.757895,NaN
3,Africa Western and Central,AFW,GDP per capita (current US$),NY.GDP.PCAP.CD,121.936832,127.451040,133.823783,139.004980,148.545883,155.561897,...,1860.727686,1630.039439,1574.230564,1720.140092,2216.385055,2030.861659,2112.794076,2138.473153,1841.855064,1411.337029
4,Angola,AGO,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,3641.728939,2051.814621,2790.718869,2860.093648,2493.678844,1759.356199,2303.908127,3682.113151,2916.136633,2665.874448

In [ ]:
value_vars=df.columns[4:]
df_long=df.melt(id_vars=['Country Name', 'Country Code'], value_vars=value_vars, var_name="Years",value_name='GDP')
df_long

                      Country Name Country Code Years          GDP
0                            Aruba          ABW  1960          NaN
1      Africa Eastern and Southern          AFE  1960   186.089204
2                      Afghanistan          AFG  1960          NaN
3       Africa Western and Central          AFW  1960   121.936832
4                           Angola          AGO  1960          NaN
...                            ...          ...   ...          ...
17285                       Kosovo          XKX  2024  7023.065985
17286                  Yemen, Rep.          YEM  2024          NaN
17287                 South Africa          ZAF  2024  6267.186814
17288                       Zambia          ZMB  2024  1187.109434
17289                     Zimbabwe          ZWE  2024  2497.203322

[17290 rows x 4 columns]

In [ ]:
df_long=df_long.dropna(subset=['GDP'])
df_long

                      Country Name Country Code Years          GDP
1      Africa Eastern and Southern          AFE  1960   186.089204
3       Africa Western and Central          AFW  1960   121.936832
9                        Argentina          ARG  1960   778.251707
13                       Australia          AUS  1960  1813.431099
14                         Austria          AUT  1960   939.914815
...                            ...          ...   ...          ...
17284                        Samoa          WSM  2024  5392.877619
17285                       Kosovo          XKX  2024  7023.065985
17287                 South Africa          ZAF  2024  6267.186814
17288                       Zambia          ZMB  2024  1187.109434
17289                     Zimbabwe          ZWE  2024  2497.203322

[14561 rows x 4 columns]

In [ ]:
df_long['Country Name'].unique()

array(['Africa Eastern and Southern', 'Africa Western and Central',
       'Argentina', 'Australia', 'Austria', 'Burundi', 'Belgium', 'Benin',
       'Burkina Faso', 'Bangladesh', 'Bahamas, The', 'Belize', 'Bermuda',
       'Bolivia', 'Brazil', 'Barbados', 'Botswana',
       'Central African Republic', 'Canada', 'Switzerland', 'Chile',
       'China', "Cote d'Ivoire", 'Cameroon', 'Congo, Dem. Rep.',
       'Congo, Rep.', 'Colombia', 'Costa Rica', 'Caribbean small states',
       'Germany', 'Denmark', 'Dominican Republic', 'Algeria',
       'East Asia & Pacific (excluding high income)',
       'Early-demographic dividend', 'East Asia & Pacific',
       'Europe & Central Asia', 'Ecuador', 'Egypt, Arab Rep.',
       'Euro area', 'Spain', 'Ethiopia', 'European Union',
       'Fragile and conflict affected situations', 'Finland', 'Fiji',
       'France', 'Gabon', 'United Kingdom', 'Ghana', 'Greece',
       'Guatemala', 'Guyana', 'High income', 'Hong Kong SAR, China',
       'Honduras', 'Heavily indebted poor countries (HIPC)', 'Haiti',
       'IBRD only', 'IDA & IBRD total', 'IDA total', 'IDA blend',
       'IDA only', 'India', 'Ireland', 'Iran, Islamic Rep.', 'Iraq',
       'Iceland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Kenya',
       'St. Kitts and Nevis', 'Korea, Rep.',
       'Latin America & Caribbean (excluding high income)', 'Liberia',
       'Libya', 'Latin America & Caribbean',
       'Least developed countries: UN classification', 'Sri Lanka',
       'Lower middle income', 'Low & middle income', 'Lesotho',
       'Late-demographic dividend', 'Luxembourg', 'Morocco', 'Madagascar',
       'Middle East, North Africa, Afghanistan & Pakistan', 'Mexico',
       'Middle income', 'Myanmar',
       'Middle East, North Africa, Afghanistan & Pakistan (excluding high income)',
       'Mauritius', 'Malaysia', 'North America', 'Niger', 'Nigeria',
       'Nicaragua', 'Netherlands', 'Norway', 'Nepal', 'New Zealand',
       'OECD members', 'Oman', 'Pakistan', 'Panama', 'Peru',
       'Philippines', 'Papua New Guinea', 'Pre-demographic dividend',
       'Puerto Rico (US)', 'Portugal', 'Paraguay',
       'Post-demographic dividend', 'Rwanda', 'South Asia',
       'Saudi Arabia', 'Sudan', 'Senegal', 'Singapore', 'Sierra Leone',
       'Somalia, Fed. Rep.', 'Sub-Saharan Africa (excluding high income)',
       'Sub-Saharan Africa', 'Suriname', 'Sweden', 'Eswatini',
       'Seychelles', 'Syrian Arab Republic', 'Chad',
       'East Asia & Pacific (IDA & IBRD countries)', 'Togo', 'Thailand',
       'Latin America & the Caribbean (IDA & IBRD countries)',
       'Middle East, North Africa, Afghanistan & Pakistan (IDA & IBRD)',
       'South Asia (IDA & IBRD)',
       'Sub-Saharan Africa (IDA & IBRD countries)', 'Trinidad and Tobago',
       'Turkiye', 'Tanzania', 'Uganda', 'Upper middle income', 'Uruguay',
       'United States', 'St. Vincent and the Grenadines', 'Venezuela, RB',
       'World', 'South Africa', 'Zambia', 'Zimbabwe', 'Arab World',
       'Mauritania', 'Tunisia', 'Equatorial Guinea', 'Kuwait',
       'Brunei Darussalam', 'Faroe Islands', 'Jordan', 'New Caledonia',
       'French Polynesia', 'El Salvador', 'Gambia, The', 'Indonesia',
       'Low income', 'Mali', 'Solomon Islands', 'Hungary', 'Andorra',
       'United Arab Emirates', 'Bahrain', 'Bhutan', 'Cuba',
       'Micronesia, Fed. Sts.', 'Guinea', 'Guinea-Bissau', 'Greenland',
       'Kiribati', 'Liechtenstein', 'Monaco', 'Maldives',
       'Marshall Islands', 'Malta', 'Nauru', 'Palau',
       'Pacific island small states', 'Qatar', 'Small states',
       'Sao Tome and Principe', 'Tuvalu', 'Samoa', 'Cyprus', 'Cambodia',
       'Other small states', 'Tonga', 'Antigua and Barbuda', 'Dominica',
       'Grenada', 'Vanuatu', 'Angola', 'Albania', 'Bulgaria', 'Comoros',
       'Cabo Verde', 'St. Lucia', 'Mongolia', 'Malawi', 'Namibia',
       'Macao SAR, China', 'Isle of Man', 'Lao PDR', 'Djibouti',
       'Viet Nam', 'Aruba',
       'Europe & Central Asia (excluding high income)', 'Georgia',
       'Romania', 'Turkmenistan', 'Ukraine', 'Uzbekistan', 'Lebanon',
       'Russian Federation',
       'Europe & Central Asia (IDA & IBRD countries)', 'Armenia',
       'Azerbaijan', 'Bosnia and Herzegovina', 'Belarus',
       'Central Europe and the Baltics', 'Czechia', 'Croatia',
       'Kazakhstan', 'Kyrgyz Republic', 'Moldova', 'North Macedonia',
       'Poland', 'Slovak Republic', 'Slovenia', 'Tajikistan',
       'Timor-Leste', 'Yemen, Rep.', 'Mozambique', 'Eritrea', 'Estonia',
       'West Bank and Gaza', 'Lithuania', 'Latvia', 'Serbia',
       'Montenegro', 'San Marino', 'Channel Islands', 'Afghanistan',
       'Curacao', 'Turks and Caicos Islands', 'American Samoa', 'Guam',
       'Northern Mariana Islands', 'Virgin Islands (U.S.)',
       'Cayman Islands', 'South Sudan', 'Kosovo',
       'Sint Maarten (Dutch part)', 'St. Martin (French part)'],
      dtype=object)

In [ ]:
encoder = LabelEncoder()

df_long['Country_Label'] = encoder.fit_transform(
    df_long['Country Name']
)
df_long

/tmp/ipykernel_10122/978249872.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_long['Country_Label'] = encoder.fit_transform(

,Country Name,Country Code,Years,GDP,Country_Label
1,Africa Eastern and Southern,AFE,1960,186.089204,1
3,Africa Western and Central,AFW,1960,121.936832,2
9,Argentina,ARG,1960,778.251707,10
13,Australia,AUS,1960,1813.431099,13
14,Austria,AUT,1960,939.914815,14
...,...,...,...,...,...
17284,Samoa,WSM,2024,5392.877619,200
17285,Kosovo,XKX,2024,7023.065985,124
17287,South Africa,ZAF,2024,6267.186814,215
17288,Zambia,ZMB,2024,1187.109434,260
17289,Zimbabwe,ZWE,2024,2497.203322,261

In [ ]:
inputs = df_long[['Country_Label', 'Years']]
target = df_long['GDP']

In [ ]:
inputs.head()

    Country_Label Years
1               1  1960
3               2  1960
9              10  1960
13             13  1960
14             14  1960

In [ ]:
target.head()

1      186.089204
3      121.936832
9      778.251707
13    1813.431099
14     939.914815
Name: GDP, dtype: float64

In [ ]:
inputs['Years'] = inputs['Years'].astype(int)

/tmp/ipykernel_10122/119407843.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inputs['Years'] = inputs['Years'].astype(int)

In [ ]:
from sklearn import tree
model = tree.DecisionTreeRegressor()

In [ ]:
model.fit(inputs, target)

DecisionTreeRegressor()

In [ ]:
model.score(inputs, target)

1.0

In [ ]:
model.predict([[0, 2020]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(

array([510.78706337])

In [ ]:
model.predict([[99, 2023]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(

array([48608.19476659])